name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Checkout code 
      uses: actions/checkout@v4 
      
    - name: Set up kind cluster 
      run: kind create cluster --name kind --wait 60s

    - name: Build Backend Image
      run: docker build -t backend:latest ./backend

    - name: Build Frontend Image
      run: docker build -t frontend:latest ./frontend

    - name: Load Images into Kind
      run: |
        kind load docker-image backend:latest
        kind load docker-image frontend:latest

    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f k8s/backend-deploy.yaml
        kubectl apply -f k8s/frontend-deploy.yaml

    - name: Scale Replicas
      run: kubectl scale deployment backend-deployment --replicas=5

    - name: Rolling Update Demo
      run: |
       kubectl set image deployment backend-deployment backend=backend:v2
       kubectl rollout status deployment backend-deployment

    
    - name: Verify Deployment
      run: kubectl get pods
